CREATE TABLE COUNTRIES AS SELECT * FROM HR.COUNTRIES,
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES,
CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS,
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS,
CREATE TABLE JOB_GRADES AS SELECT * FROM HR.JOB_GRADES,
CREATE TABLE REGIONS AS SELECT * FROM HR.REGIONS,
CREATE TABLE LOCATIONS AS SELECT * FROM HR.LOCATIONS,


CREATE VIEW widok1 AS SELECT last_name || ' ' || salary AS wynagrodzenie
FROM employees
WHERE department_id IN (20, 50)
  AND salary BETWEEN 2000 AND 7000
ORDER BY last_name;

CREATE VIEW widok2 AS
SELECT hire_date, last_name, &podajkol
FROM employees
WHERE MANAGER_ID IS NOT NULL
  AND EXTRACT(YEAR FROM hire_date) = 2005
ORDER BY podajkol;

CREATE VIEW widok3 AS 
SELECT first_name || ' ' || last_name AS full_name, salary, phone_number
FROM employees
WHERE last_name LIKE '__e%'
  AND first_name LIKE '%' || &userinput || '%'
ORDER BY 1 DESC, 2 ASC;

CREATE VIEW widok4 AS SELECT 
    first_name || ' ' || last_name AS full_name, 
    ROUND(MONTHS_BETWEEN(SYSDATE, hire_date)) AS months_worked, 
    CASE 
		WHEN months_worked < 150 THEN salary * 1.1
		WHEN months_worked BETWEEN 150 AND 200 THEN salary * 1.2
		WHEN months_worked > 200 THEN salary * 1.3
        ELSE salary * 1
    END AS wysokość_dodatku
FROM employees ORDER BY months_worked;

CREATE VIEW widok5 AS
SELECT DEPARTMENTS.DEPARTMENT_NAME, SUM(SALARY) AS suma, AVG(SALARY) AS srednia FROM DEPARTMENTS AS Dep, JOB_HISTORY AS Jobh, JOBS AS J, EMPLOYEES AS enp
WHERE Dep.DEPARTMENT_ID = Jobh.DEPARTMENT_ID AND Jobh.JOB_ID = J.JOB_ID AND enp.DEPARTMENT_ID = Dep.DEPARTMENT_ID AND enp.JOB_ID = J.JOB_ID AND J.MIN_SALARY > 5000
GROUP BY DEPARTMENT.NAME;

CREATE VIEW widok6 AS
SELECT last_name, DEPARTMENT_ID, DEPARTMENT_NAME, JOB_ID FROM LOCATIONS AS Loc, EMPLOYEES AS Emp, DEPARTMENTS AS Dep WHERE Emp.DEPARTMENT_ID = Dep.DEPARTMENT_ID AND Loc.LOCATION_ID = Dep.LOCATION_ID AND CITY = "Toronto";

CREATE VIEW widok7 AS
SELECT first_name, last_name FROM EMPLOYEES AS Emp, DEPARTMENTS AS Dep WHERE Dep.DEPARTMENT_ID = Emp.DEPARTMENT_ID AND Dep.DEPARTMENT_ID = (SELECT * FROM EMPLOYEES WHERE first_name = "Jennifer")

CREATE VIEW widok8 AS
SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE 