CREATE TABLE COUNTRIES AS SELECT * FROM HR.COUNTRIES,
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES,
CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS,
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS,
CREATE TABLE JOB_GRADES AS SELECT * FROM HR.JOB_GRADES,
CREATE TABLE REGIONS AS SELECT * FROM HR.REGIONS,
CREATE TABLE LOCATIONS AS SELECT * FROM HR.LOCATIONS,


CREATE VIEW widok1 AS SELECT last_name || ' ' || salary AS wynagrodzenie
FROM employees
WHERE department_id IN (20, 50)
  AND salary BETWEEN 2000 AND 7000
ORDER BY last_name;

CREATE VIEW widok2 AS
SELECT hire_date, last_name, salary
FROM employees
WHERE MANAGER_ID IS NOT NULL
  AND EXTRACT(YEAR FROM hire_date) = 2005
ORDER BY salary;
